services:
  mysqldb:
    image: mysql
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASS
      - MYSQL_DATABASE=$DB_NAME
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT

  app:
    build: .
    depends_on:
      - mysqldb
    links:
      - mysqldb
    ports:
      - 3000:3000